### ISSUE TITLE
error

### ISSUE THREAD

**Issue by adminlove520** [51ak/ChatGPT_Weixin#1]
config文件没传吧 兄弟  报错了呢
![image](https://user-images.githubusercontent.com/32920883/208819437-22c18097-8f28-4e1c-8588-ff23db86be9e.png)

**Comment by wqw547243068** [comment]
> config文件没传吧 兄弟 报错了呢 ![image](https://user-images.githubusercontent.com/32920883/208819437-22c18097-8f28-4e1c-8588-ff23db86be9e.png)

作者传了个半成品上来。。。。囧

**Comment by 51ak** [comment]
config.py 里存放的是token key ,是个配置.  这个key 需要用到在chatgpt官网上申请过来的.每个人用的不一样.所以这个配置没上传

```
config.py:

TOKEN=" " # 微信公众号的token
OPENAI_KEY=""  # chatgpt的token 


```
